name: pull-request-workflow 2
on: pull_request

jobs:
  push-job: 
    runs-on: ubuntu-latest
    steps: 
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo test